# Generated by Django 4.2.2 on 2023-08-26 10:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 11, 19, 4, 335635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 10, 29, 4, 335635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
