# Generated by Django 4.2.2 on 2023-08-26 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_token_access_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 11, 27, 46, 367565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 10, 37, 46, 367565, tzinfo=datetime.timezone.utc)),
        ),
    ]
