# Generated by Django 4.2.2 on 2023-08-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_token_access_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 11, 48, 33, 719318, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 10, 58, 33, 719318, tzinfo=datetime.timezone.utc)),
        ),
    ]
