# Generated by Django 4.2.2 on 2023-08-26 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 12, 31, 21, 588879, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 11, 41, 21, 588879, tzinfo=datetime.timezone.utc)),
        ),
    ]
